<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tittle_DaftarProdukmuYangDitawar</name>
   <tag></tag>
   <elementGuidId>ed222006-d83f-49ff-9be6-406ab8c136c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.title.mt-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>1dceed6e-f839-4cff-a4c5-8318b541d3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title mt-3</value>
      <webElementGuid>0a32f68d-ca42-4b6b-a430-0fbc02a7570d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Produkmu yang Ditawar</value>
      <webElementGuid>65bf2d62-a4cf-4034-aea6-efe98dcc3ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row mt-5&quot;]/div[@class=&quot;col-md-6&quot;]/h6[@class=&quot;title mt-3&quot;]</value>
      <webElementGuid>4f011bb7-fdff-4aa9-9333-c845e91d739d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/h6</value>
      <webElementGuid>eb48a16e-4ed6-4f8d-aac3-08ec5cd38a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='indra'])[1]/following::h6[1]</value>
      <webElementGuid>4d79de6f-e363-46f1-a7d8-6ee74a4b28c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::h6[1]</value>
      <webElementGuid>bcd9abfc-dc16-47a8-8fe5-8b71d255624d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penawaran produk'])[1]/preceding::h6[1]</value>
      <webElementGuid>60df7791-1e2a-475a-9bc0-41eadd394fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indra Produk 2'])[2]/preceding::h6[1]</value>
      <webElementGuid>89b2f40b-d2ee-4af3-be1a-5a30ace85207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Produkmu yang Ditawar']/parent::*</value>
      <webElementGuid>d7d2be34-9c35-443a-9fa4-8b2d6326f259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>ff231568-f063-418b-9d24-7c7252f92fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Daftar Produkmu yang Ditawar' or . = 'Daftar Produkmu yang Ditawar')]</value>
      <webElementGuid>3854dc91-81b8-492b-b47a-a32aad3d2d10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
